# Generated by Django 4.2 on 2023-05-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0002_orderform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
