# Generated by Django 4.2 on 2023-06-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0005_accounts_delete_orderform_delete_requestform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edetail', models.CharField(max_length=250, verbose_name='Event detail')),
                ('etype', models.CharField(max_length=40, verbose_name='Event type')),
                ('edate', models.DateField(verbose_name='Event date')),
                ('starttime', models.TimeField(verbose_name='Event Start Time')),
                ('endtime', models.TimeField(verbose_name='Event End Time')),
                ('noguest', models.IntegerField(verbose_name='Number of Guest')),
                ('etheme', models.CharField(max_length=70, verbose_name='Event theme')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full name of Client')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('phonenum', models.CharField(max_length=11, verbose_name='Phone number')),
            ],
        ),
    ]
