# Generated by Django 4.2 on 2023-06-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0006_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='NatureParkReservation',
        ),
    ]
