# Generated by Django 4.2 on 2023-06-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0007_rename_reservation_natureparkreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('ALBARRACIN', 'ALBARRACIN'), ('BIRONDO', 'BIRONDO'), ('CEUVAS', 'CUEVAS'), ('LARGO', 'LARGO'), ('YBANEZ', 'YBANEZ'), ('LASOLA', 'LASOLA'), ('SAYSON', 'SAYSON')], max_length=50)),
                ('phone', models.IntegerField()),
                ('Rdate', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.CharField(choices=[('price300', '300'), ('price500', '500'), ('price250-300', '250-300'), ('price400-500', '400-500'), ('price400', '400')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('numberOfGuest', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
                ('checkInDate', models.CharField(max_length=50)),
                ('modeofpayment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EcobayForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('numberofguest', models.IntegerField()),
                ('date', models.DateField()),
                ('modeOfpayment', models.CharField(choices=[('gcash', 'Gcash'), ('MetroBank', 'Metro Bank')], max_length=50)),
                ('venue', models.CharField(choices=[('ElizabethHall', 'Elizabeth Hall'), ('AlexanderHall', 'Alexander Hall'), ('OpenSpaceVenue', 'Open Space Venue')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaayoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('CreditCard', 'Credit Card'), ('Others', 'Others')], max_length=50)),
                ('RoomNum', models.IntegerField()),
                ('ArrivalDate', models.DateField()),
                ('NumPerson', models.IntegerField()),
                ('WakeCall', models.TimeField()),
                ('RoomRate', models.IntegerField()),
                ('DepartureDate', models.DateField()),
                ('Adults', models.IntegerField()),
                ('Kids', models.IntegerField()),
                ('CheckInTime', models.TimeField()),
                ('GuestName', models.CharField(max_length=100)),
                ('Accompany', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('CompNameGroup', models.CharField(max_length=200)),
                ('Addr', models.CharField(max_length=200)),
                ('VehicleNum', models.IntegerField()),
                ('Nationality', models.CharField(max_length=50)),
                ('ContactNum', models.IntegerField()),
                ('PassportNum', models.IntegerField()),
                ('EAddr', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MaayoRF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('CreditCard', 'Credit Card'), ('Others', 'Others')], max_length=50)),
                ('RoomNum', models.IntegerField()),
                ('ArrivalDate', models.DateField()),
                ('NumPerson', models.IntegerField()),
                ('WakeCall', models.TimeField()),
                ('RoomRate', models.IntegerField()),
                ('DepartureDate', models.DateField()),
                ('Adults', models.IntegerField()),
                ('Kids', models.IntegerField()),
                ('CheckInTime', models.TimeField()),
                ('GuestName', models.CharField(max_length=200)),
                ('Accompany', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('CompNameGroup', models.CharField(max_length=200)),
                ('Addr', models.CharField(max_length=200)),
                ('VehicleNum', models.IntegerField()),
                ('Nationality', models.CharField(max_length=50)),
                ('ContactNum', models.IntegerField()),
                ('PassportNum', models.IntegerField()),
                ('EAddr', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SeabreezeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('CreditCard', 'Credit Card'), ('Others', 'Others')], max_length=50)),
                ('RoomNum', models.IntegerField()),
                ('ArrivalDate', models.DateField()),
                ('DepartureDate', models.DateField()),
                ('Adults', models.IntegerField()),
                ('Kids', models.IntegerField()),
                ('CheckInTime', models.TimeField()),
                ('CheckOutTime', models.TimeField()),
                ('GuestName', models.CharField(max_length=100)),
                ('CompNameGroup', models.CharField(max_length=200)),
                ('Addr', models.CharField(max_length=200)),
                ('ContactNum', models.IntegerField()),
                ('EAddr', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('numberofguest', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('modeOfpayment', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='middlename',
        ),
    ]
