# Generated by Django 4.2 on 2023-06-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0009_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
