# Generated by Django 4.2 on 2023-06-12 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0010_accounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venue',
            new_name='EcoBay',
        ),
    ]
