# Generated by Django 4.2 on 2023-06-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0011_rename_venue_ecobay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcoBay',
            new_name='EcoBayVenueRF',
        ),
    ]
