# Generated by Django 4.2 on 2023-06-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0012_rename_ecobay_ecobayvenuerf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='EcoBayBooking',
        ),
    ]
