# Generated by Django 4.2 on 2023-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0013_rename_booking_ecobaybooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcobayForm',
        ),
        migrations.AlterField(
            model_name='ecobayvenuerf',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ecobayvenuerf',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ecobayvenuerf',
            name='modeOfpayment',
            field=models.CharField(choices=[('gcash', 'Gcash'), ('MetroBank', 'Metro Bank')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ecobayvenuerf',
            name='numberofguest',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ecobayvenuerf',
            name='venue',
            field=models.CharField(choices=[('ElizabethHall', 'Elizabeth Hall'), ('AlexanderHall', 'Alexander Hall'), ('OpenSpaceVenue', 'Open Space Venue')], max_length=50),
        ),
    ]
