# Generated by Django 4.2 on 2023-06-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity1', '0014_delete_ecobayform_alter_ecobayvenuerf_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extreme_Reservation',
            fields=[
                ('reservation_reference', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('reserved_activity', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('no_of_adults', models.CharField(max_length=50)),
                ('no_of_children', models.CharField(max_length=50)),
                ('reservation_date', models.CharField(max_length=50)),
                ('reservation_time', models.CharField(max_length=50)),
                ('mode_of_payment', models.CharField(max_length=50)),
            ],
        ),
    ]
